# Generated by Django 5.0.6 on 2024-07-28 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmroller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollconfig',
            name='name',
            field=models.TextField(default='test', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rollresult',
            name='roll_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmroller.rollconfig'),
        ),
    ]
