# Generated by Django 5.0.6 on 2024-07-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmroller', '0002_rollconfig_name_alter_rollresult_roll_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollconfig',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rollresult',
            name='roll_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dmroller.rollconfig'),
            preserve_default=False,
        ),
    ]
