# Generated by Django 5.0.6 on 2024-08-04 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmroller', '0003_alter_rollconfig_name_alter_rollresult_roll_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
