# Generated by Django 5.0.6 on 2024-08-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmroller', '0004_rollresult_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollresult',
            name='prettify',
            field=models.TextField(default='foo'),
            preserve_default=False,
        ),
    ]
