[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "diceroller"
version = "1.0.0"
description = "A d20-based dicerolling utility"
authors = []
readme = "README.md"
requires-python = ">=3.7"
dependencies = []